### ISSUE TITLE
Bug with redstone power & Light Penetration

### ISSUE THREAD

**Issue by TheFoolKila** [DcZipPL/LightestLampsFabric#1]
It seems that with the Delta and Gamma lamps toggling redstone power off light penetration still seems to be active.

I assume this is not the correct functionality since it says "Redstone Inverted"

**Comment by TheFoolKila** [comment]
I assume this is released with the latest commit? Still needs a CF release.

**Comment by DcZipPL** [comment]
Yes it needs. I'm now bug hunting moon shard drop.

**Comment by DcZipPL** [comment]
If issue still occur. Please reopen this issue.
