### ISSUE TITLE
Config File is empty, and changing the config in the mod menu doesnt seem to work correctly [Fabric] 1.18.2

### ISSUE THREAD

**Issue by KingSnailtan** [DcZipPL/LightestLampsFabric#4]
lightest-lamps.json5 only contains "{}"

turning on vanilla mode in the ingame mod menu settings still makes it require power

Passive mode does work, but the others dont. Switching to them makes passive mode stop working.
Breaking and replacing the block makes it work again

**Comment by KingSnailtan** [comment]
It does work on the multiplier though

**Comment by DcZipPL** [comment]
Fixed in e547438897cd54d5d55d11322dbb452a979a6205. Replaced JSON file with working TOML.

Thank you.
